package com.monk.commondas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-08-06T16:01:21.030+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://monk.com/CommonDAS", name = "CommonDAS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CommonDAS {

    @WebMethod(action = "process")
    @WebResult(name = "OutputParameters", targetNamespace = "http://monk.com/CommonDAS", partName = "payload")
    public OutputParameters process(
        @WebParam(partName = "payload", name = "InputParameters", targetNamespace = "http://monk.com/CommonDAS")
        InputParameters payload
    );
}
