server:
   port: 8084
   servlet:
      context-path: /web4
      
spring:
   thymeleaf:
      prefix: classpath:/static/
      suffix: .html
      cache: false #关闭缓存'
      
proxy:
   mft:
      targetUri: http://localhost:8082/web2