version: "3"
services:
  nacos1:
    image: nacos/nacos-server:latest
    container_name: nacos1
    networks:
      nacos_net:
        ipv4_address: 192.18.0.10
    volumes:
      - ../volumes/cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ./cluster-config.properties
    restart: on-failure
    depends_on:
      - mysql

  nacos2:
    image: nacos/nacos-server:latest
    container_name: nacos2
    networks:
      nacos_net:
        ipv4_address: 192.18.0.11
    volumes:
      - ../volumes/cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8849:8848"
    env_file:
      - ./cluster-config.properties
    restart: always
    depends_on:
      - mysql
  nacos3:
    image: nacos/nacos-server:latest
    container_name: nacos3
    networks:
      nacos_net:
        ipv4_address: 192.18.0.12
    volumes:
      - ../volumes/cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8850:8848"
    env_file:
      - ./cluster-config.properties
    restart: always
    depends_on:
      - mysql
  mysql:
    container_name: nacos-mysql
    image: nacos/nacos-mysql:8.0.16
    networks:
      nacos_net:
        ipv4_address: 192.18.0.13
    env_file:
      - ../env/mysql.env
    volumes:
      - ../volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
    nacos_net:
        external:
            name: mynetwork